title: My page
author: David Bonito Vieira
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my page.

# social links
twitter_username: twitterhandle # DO NOT include the @ character, or else the build will fail!
github_username:  githubhandle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
